<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~@s</string>
	<key>name</key>
	<string>SuperCollider</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(if|do|for|^|var|this|true|false)\b</string>
			<key>name</key>
			<string>keyword.control.untitled</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\\[a-zA-Z0-9\_]+</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\~[a-zA-Z0-9]+</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\|[a-zA-Z0-9\_\=\.\(\)[[:space:]]\,]+\|</string>
			<key>name</key>
			<string>entity.name.tag</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[[:space:]]+([a-z]{1}[a-zA-Z0-9_]+) {</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[[:space:]]+\*([a-z]{1}[a-zA-Z0-9_]+) {</string>
			<key>name</key>
			<string>support.constant</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\/\/.*</string>
			<key>name</key>
			<string>comment</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.untitled</string>
	<key>uuid</key>
	<string>F63E530D-4C84-4C66-9EAA-6FC504FA4587</string>
</dict>
</plist>
